name: smm4h2026
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.10,<3.13
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - jupyterlab
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - transformers>=4.39
      - datasets>=2.18
      - accelerate>=0.27
      - evaluate>=0.4
      - sentencepiece>=0.1.99
      - sacremoses
      - psutil
